export const metadata = {
  title: 'crew',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
          {children}
      </>
    )
  }