import { Navbar } from '@/components'
import './globals.css'


export const metadata = {
  title: 'space tourism',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
        {children}
      </body>
    </html>
  )
}
