import { Navbar } from '@/components'
import './globals.css'


export const metadata = {
  title: 'space tourism',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen  flex flex-col p-6  tablet:pl-6 tablet:pr-0 tablet:py-0 bg-no-repeat bg-cover bg-background-home-m tablet:bg-no-repeat tablet:bg-cover tablet:bg-background-home-t">
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
