export const desInfo:{title:string,content:string,AvgDistance:string,EstTravelTime:string}[]=[
    {title: "MOON", 
    content: "See our planet as you’ve never seen it before. A perfect relaxing trip away to help regain perspective and come back refreshed.",
    AvgDistance: "384,400 KM",
    EstTravelTime: "3 Days",},
    {title: "MARS", 
    content: "Don’t forget to pack your hiking boots. You’ll need them to tackle Olympus Mons, the tallest planetary mountain in our solar system. It’s two and a half times the size of Everest",
    AvgDistance: "225 MIL.KM",
    EstTravelTime: "9 months",},
    {title: "EUROPA", 
    content: "The smallest of the four Galilean moons orbiting Jupiter, Europa is a winter lover’s dream. With an icy surface, it’s perfect for a bit of ice skating, curling, hockey, or simple relaxation in your snug wintery cabin.",
    AvgDistance: "628 MIL.KM",
    EstTravelTime: "3 years",},
    {title: "TITAN", 
    content: "The only moon known to have a dense atmosphere other than Earth, Titan is a home away from home (just a few hundred degrees colder!). As a bonus, you get striking views of the Rings of Saturn.",
    AvgDistance: "1.6 BIL.KM",
    EstTravelTime: "7 years",},
]